name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Build flutter web app
        run: flutter build web --release --base-href /MyFitnessRank/
      - name: Deploy to GitHub Pages
        uses: bluefireteam/flutter-gh-pages@v9
        with:
          baseHref: /MyFitnessRank/